# Generated by Django 5.0.3 on 2024-03-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='caracteristicas/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('año', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('imagen', models.ImageField(upload_to='vehiculos/')),
                ('ficha_tecnica', models.FileField(upload_to='fichas_tecnicas/')),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Auto'), ('pickup', 'Pickup'), ('comercial', 'Comercial'), ('suv', 'SUV'), ('crossover', 'Crossover')], max_length=20)),
                ('colores', models.ManyToManyField(to='egoapi.color')),
                ('especificaciones', models.ManyToManyField(to='egoapi.especificaciones')),
            ],
        ),
    ]
